/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { Quiz } from './components/Quiz';
import { Sparkles, HelpCircle, Code2, Copy, Check, Disc3, ExternalLink } from 'lucide-react';
import { isSupabaseConfigured } from './lib/supabase';

export default function App() {
  const [showConfigModal, setShowConfigModal] = useState(false);
  const [copiedSql, setCopiedSql] = useState(false);

  const supabaseSql = `-- Create the leaderboard table in your Supabase SQL Editor:
create table public.leaderboard (
  id bigint generated by default as identity primary key,
  username text not null,
  score integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.leaderboard enable row level security;

-- Allow public read access
create policy "Public leaderboard read" on public.leaderboard
  for select using (true);

-- Allow public score submission
create policy "Public leaderboard insert" on public.leaderboard
  for insert with check (true);

-- Allow public score updates when playing again
create policy "Public leaderboard update" on public.leaderboard
  for update using (true);`;

  const copySql = () => {
    navigator.clipboard.writeText(supabaseSql);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 2000);
  };

  return (
    <div className="min-h-screen bg-[#090314] text-slate-100 flex flex-col justify-between selection:bg-pink-500 selection:text-white font-sans antialiased relative overflow-x-hidden">
      {/* Dynamic Bollywood ambient background glow */}
      <div className="fixed inset-0 pointer-events-none z-0">
        <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-gradient-to-br from-pink-600/15 via-purple-700/10 to-transparent rounded-full blur-[120px]" />
        <div className="absolute bottom-10 right-1/4 w-[550px] h-[550px] bg-gradient-to-tl from-purple-800/20 via-amber-600/10 to-transparent rounded-full blur-[130px]" />
      </div>

      {/* Main Header / Nav */}
      <header className="relative z-10 w-full border-b border-purple-900/40 bg-[#0c041b]/80 backdrop-blur-md">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-pink-500 to-amber-400 flex items-center justify-center shadow-md shadow-pink-500/20">
              <Disc3 className="w-5 h-5 text-slate-950 animate-spin [animation-duration:8s]" />
            </div>
            <div className="flex items-baseline gap-2">
              <span className="font-extrabold text-base sm:text-lg tracking-tight text-white">
                Bollywood<span className="text-pink-400">Beat</span>
              </span>
              <span className="text-[11px] font-semibold text-amber-400/90 hidden sm:inline">
                5-Second iTunes Edition
              </span>
            </div>
          </div>

          <div className="flex items-center gap-3">
            {/* Supabase connection indicator badge */}
            <button
              onClick={() => setShowConfigModal(true)}
              className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-medium border border-purple-800/60 bg-purple-950/40 hover:bg-purple-900/40 text-purple-200 transition-colors"
            >
              <span
                className={`w-2 h-2 rounded-full ${
                  isSupabaseConfigured ? 'bg-emerald-400 shadow-sm shadow-emerald-400/50' : 'bg-amber-400'
                }`}
              />
              <span className="hidden xs:inline">
                {isSupabaseConfigured ? 'Supabase Connected' : 'Supabase Setup'}
              </span>
              <HelpCircle className="w-3.5 h-3.5 text-purple-400" />
            </button>
          </div>
        </div>
      </header>

      {/* Main Content: The Quiz Component */}
      <main className="relative z-10 flex-1 flex flex-col justify-center items-center py-4 sm:py-8">
        <Quiz />
      </main>

      {/* Footer */}
      <footer className="relative z-10 w-full border-t border-purple-900/30 bg-[#070210]/90 py-5 text-center text-xs text-purple-400/70">
        <div className="max-w-5xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-2">
          <div>
            Powered by Apple iTunes Search API & Supabase Leaderboard
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={() => setShowConfigModal(true)}
              className="hover:text-pink-300 transition-colors cursor-pointer"
            >
              Database Instructions
            </button>
            <span aria-hidden="true">·</span>
            <span>Bollywood Night Theme</span>
          </div>
        </div>
      </footer>

      {/* Supabase Setup / Instructions Modal */}
      {showConfigModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md">
          <div className="relative w-full max-w-lg bg-[#120626] border border-pink-500/30 rounded-2xl p-6 shadow-2xl text-white">
            <div className="flex items-center justify-between pb-3 border-b border-purple-800/60 mb-4">
              <div className="flex items-center gap-2">
                <Code2 className="w-5 h-5 text-amber-400" />
                <h3 className="text-base font-bold text-white">Supabase Leaderboard Setup</h3>
              </div>
              <button
                onClick={() => setShowConfigModal(false)}
                className="text-purple-400 hover:text-white p-1"
              >
                ✕
              </button>
            </div>

            <p className="text-xs text-purple-200 mb-4 leading-relaxed">
              This app includes built-in offline/localStorage persistence that works immediately. To enable live cloud sync with your personal Supabase account:
            </p>

            <ol className="text-xs text-purple-300 space-y-2.5 mb-4 list-decimal list-inside">
              <li>
                Create a free project at{' '}
                <a
                  href="https://supabase.com"
                  target="_blank"
                  rel="noreferrer"
                  className="text-pink-400 underline inline-flex items-center gap-0.5"
                >
                  supabase.com <ExternalLink className="w-3 h-3" />
                </a>
              </li>
              <li>
                In your Supabase SQL Editor, run the table schema below to create the <code className="text-amber-300">leaderboard</code> table:
              </li>
            </ol>

            <div className="relative bg-purple-950/70 rounded-xl p-3 border border-purple-800/60 font-mono text-[11px] text-purple-200 max-h-40 overflow-y-auto mb-4">
              <button
                onClick={copySql}
                className="absolute top-2 right-2 px-2 py-1 bg-purple-800/80 hover:bg-purple-700 text-amber-300 rounded flex items-center gap-1 text-[10px]"
              >
                {copiedSql ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                {copiedSql ? 'Copied!' : 'Copy SQL'}
              </button>
              <pre>{supabaseSql}</pre>
            </div>

            <ol start={3} className="text-xs text-purple-300 space-y-2 mb-5 list-decimal list-inside">
              <li>
                In your environment variables or <code className="text-pink-300">.env</code>, provide:
                <div className="mt-1 bg-black/40 p-2 rounded text-[11px] font-mono text-purple-200">
                  VITE_SUPABASE_URL=your_project_url<br />
                  VITE_SUPABASE_ANON_KEY=your_anon_key
                </div>
              </li>
            </ol>

            <div className="flex justify-end">
              <button
                onClick={() => setShowConfigModal(false)}
                className="px-4 py-2 bg-gradient-to-r from-pink-600 to-purple-600 hover:from-pink-500 hover:to-purple-500 rounded-xl text-xs font-bold text-white shadow"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
